config/routes.rb
CloudGui::Application.routes.draw do
  resources :instances

  root :to => 'instances#index'

end

app/models/instance.rb
class Instance < ActiveRecord::Base
  attr_accessible :baseimage, :cpus, :hostname, :ipaddr, :memory, :usercomment

  # CPU_SIZES = [ 1, 2 ]
  # MEMORY_SIZES = [ 512, 1024, 2048 ]
  # IMAGES = [ "CentOS 6", "RHEL 6", "Ubuntu 10.04"]

  validates :baseimage, :cpus, :memory, :usercomment, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  # GET /instances
  # GET /instances.json
  def index
    @instances = Instance.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @instances }
    end
  end

  # GET /instances/1
  # GET /instances/1.json
  def show
    @instance = Instance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instance }
    end
  end

  # GET /instances/new
  # GET /instances/new.json
  def new
    @instance = Instance.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @instance }
    end
  end

  # GET /instances/1/edit
  def edit
    @instance = Instance.find(params[:id])
  end

  # POST /instances
  # POST /instances.json
  def create
    @instance = Instance.new(params[:instance])

    respond_to do |format|
      if @instance.save

        system("ssh root@#{CloudGui::Application.config.hypervisor_ip} \"exec /data/cloud/scripts/provision.sh #{params[:instance][:cpus]} #{params[:instance][:memory]} #{params[:instance][:baseimage]} 2>&1 | tee /data/cloud/logs/cloud_gui.log\"")

        format.html { redirect_to @instance, notice: 'Instance was successfully created.' }
        format.json { render json: @instance, status: :created, location: @instance }
      else
        format.html { render action: "new" }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /instances/1
  # PUT /instances/1.json
  def update
    @instance = Instance.find(params[:id])

    respond_to do |format|
      if @instance.update_attributes(params[:instance])
        format.html { redirect_to @instance, notice: 'Instance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instances/1
  # DELETE /instances/1.json
  def destroy
    @instance = Instance.find(params[:id])
    @instance.destroy

    respond_to do |format|
      format.html { redirect_to instances_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/_form.html.erb
<%= form_for(@instance) do |f| %>
  <% if @instance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instance.errors.count, "error") %> prohibited this instance from being saved:</h2>

      <ul>
      <% @instance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usercomment %><br />
    <%= f.text_field :usercomment %>
  </div>
  <div class="field">
    <%= f.label :baseimage %><br />
    <%= f.select :baseimage, CloudGui::Application.config.images %>
  </div>
  <div class="field">
    <%= f.label :cpus %><br />
    <%= f.select :cpus, CloudGui::Application.config.cpu_sizes %>
  </div>
  <div class="field">
    <%= f.label :memory %><br />
    <%= f.select :memory, CloudGui::Application.config.memory_sizes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instances/edit.html.erb
<h1>Editing instance</h1>

<%= render 'form' %>

<%= link_to 'Show', @instance %> |
<%= link_to 'Back', instances_path %>

app/views/instances/index.html.erb
<h1>Listing instances</h1>

<table>
  <tr>
    <th>User Comment</th>
    <th>Hostname</th>
    <th>IP Address</th>
    <th>Base Image</th>
    <th>CPUs</th>
    <th>Memory</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @instances.each do |instance| %>
  <tr>
    <td><%= instance.usercomment %></td>
    <td><%= instance.hostname %></td>
    <td><%= instance.ipaddr %></td>
    <td><%= instance.baseimage %></td>
    <td><%= instance.cpus %></td>
    <td><%= instance.memory %></td>
    <td><%= link_to 'Show', instance %></td>
    <td><%= link_to 'Edit', edit_instance_path(instance) %></td>
    <td><%= link_to 'Destroy', instance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Instance', new_instance_path %>

app/views/instances/new.html.erb
<h1>New instance</h1>

<%= render 'form' %>

<%= link_to 'Back', instances_path %>

app/views/instances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Usercomment:</b>
  <%= @instance.usercomment %>
</p>

<p>
  <b>Hostname:</b>
  <%= @instance.hostname %>
</p>

<p>
  <b>Ipaddr:</b>
  <%= @instance.ipaddr %>
</p>

<p>
  <b>Baseimage:</b>
  <%= @instance.baseimage %>
</p>

<p>
  <b>Cpus:</b>
  <%= @instance.cpus %>
</p>

<p>
  <b>Memory:</b>
  <%= @instance.memory %>
</p>


<%= link_to 'Edit', edit_instance_path(@instance) %> |
<%= link_to 'Back', instances_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CloudGui</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>